export default {
  server: {
    host: '0.0.0.0',
    port: parseInt(process.env.NODELINK_PORT || '2333'),
    password: process.env.NODELINK_PASSWORD || 'youshallnotpass',
  },
  logging: {
    level: process.env.NODELINK_LOG_LEVEL || 'info',
  },
  cluster: { enabled: false },
  maxSearchResults: 10,
  maxAlbumPlaylistLength: 100,
  playerUpdateInterval: 2000,
  statsUpdateInterval: 30000,
  trackStuckThresholdMs: 10000,
  eventTimeoutMs: 15000,
  zombieThresholdMs: 60000,
  defaultSearchSource: ['youtube', 'soundcloud'],
  audio: { quality: 'high' },
  sources: {
    youtube: { enabled: true },
    soundcloud: { enabled: true },
    spotify: {
      enabled: true,
      clientId: process.env.SPOTIFY_CLIENT_ID || '',
      clientSecret: process.env.SPOTIFY_CLIENT_SECRET || '',
      playlistLoadLimit: 1,
      albumLoadLimit: 1,
      playlistPageLoadConcurrency: 10,
      albumPageLoadConcurrency: 5,
      allowExplicit: true,
      allowLocalFiles: false,
    },
    applemusic: {
      enabled: true,
      playlistLoadLimit: 0,
      albumLoadLimit: 0,
      playlistPageLoadConcurrency: 5,
      albumPageLoadConcurrency: 5,
      allowExplicit: true,
    },
  },
};
